### ISSUE TITLE
group3 : workflows : intro

### ISSUE THREAD

**Issue by ahlamboudali** [BF-FrontEnd-class-2024/home#60]
- [x] [repo](https://github.com/BF-FrontEnd-class-2024/group3-intro)
- [x] [many small, well-named commits](https://github.com/BF-FrontEnd-class-2024/group3-intro/actions)
- [x] a nice README
- [x] one well-named file per person
- [x] [one pull requests for each group member](https://github.com/BF-FrontEnd-class-2024/group3-intro/pulls?q=is%3Apr+is%3Aclosed)
  - [x] linting checks pass
  - [x] code review checklist is complete
  - [x] the reviewer merged the code

**Comment by rathiNamrata** [comment]
I have cloned home repo and created empty readme file and checkin from my local branch
